// Find

Monarch.cpp ItemIDRangeManager.cpp ClientManagerHorseName.cpp version.cpp \

// Add Below or add to your side for example = > Monarch.cpp ItemIDRangeManager.cpp ClientManagerHorseName.cpp version.cpp RedCoinManager.cpp \

RedCoinManager.cpp